[project]
name = "notebooks"
version = "0.1.0"
description = "Collection of Notebooks"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "basedpyright>=1.39.0",
    "marimo[mcp,recommended]>=0.23.1",
    "numpy>=2.4.4",
]

[dependency-groups]
dev = [
    "duckdb>=1.5.2",
    "polars[pyarrow]>=1.39.3",
    "sqlglot>=30.4.3",
]
